version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/sourcepoint_unified_cmp"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/sourcepoint_unified_cmp/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/sourcepoint_unified_cmp_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/sourcepoint_unified_cmp_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/sourcepoint_unified_cmp_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle" 
    directory: "/packages/sourcepoint_unified_cmp_android/android" 
    schedule:
      interval: "daily"
  - package-ecosystem: "swift" 
    directory: "/packages/sourcepoint_unified_cmp_ios/ios" 
    schedule:
      interval: "daily"