
name: sourcepoint_unified_cmp

packages:
  - packages/*
  - packages/*/example

sdkPath: .fvm/flutter_sdk

command:
  clean:
    hooks:
      # Runs "flutter clean" in all Flutter packages (`--flutter`)
      # with a concurrency of 3 at a time (`--concurrency=3`).
      post: melos exec --flutter --concurrency=3 -- "fvm flutter clean"
  version:
    # Generate commit links in package changelogs.
    #linkToCommits: true
    # # Only allow versioning to happen on main branch.
    # branch: master
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true
    
scripts:
  analyze:
    exec: fvm flutter analyze .

  pana:
    exec: fvm exec pana . --no-warning

  format:
    run: |
      melos format && \
      swiftformat . && \
      ktlint --format '**/*.kt' '**/*.kts' '!**/*.g.kt' 
    description: |
       - Requires `swiftformat` (can be installed via Brew on macOS).
       - Requires `ktlint` (can be installed via Brew on macOS).

  test:all:
    run: |
      melos run test --no-select
    description: |
      Run all tests available.

  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "fvm flutter test --coverage"
    description: Run `flutter test` for a specific package.
    packageFilters:
      dirExists:
        - test
      ignore:
        - '*example*'

  generate:pigeon:
    run: |
      melos exec -- "fvm flutter pub run pigeon --input ./pigeons/messages.dart" && \
      melos run format --no-select
    packageFilters:
      fileExists: 'pigeons/messages.dart'
    description: Generate the pigeon messages for supported packages.

  generate:pigeon:all:
    run: |
      melos run generate:pigeon --no-select
    description: Generate the pigeon messages for all the supported packages.

  generate:mocks:
    run: |
      melos exec -- "fvm flutter pub run build_runner build --delete-conflicting-outputs" && \
      melos run format --no-select
    packageFilters:
      dependsOn:
        - build_runner
    description: Generate mocks for tests.

  generate:mocks:all:
    run: |
      melos run generate:mocks --no-select
    description: Generate mocks for all tests.

  run:example:
    run: fvm flutter run
    description: Run the example app.
    exec:
      concurrency: 1
    packageFilters:
        scope: 'sourcepoint_unified_cmp_example'
