name: sourcepoint_unified_cmp_ios
description: flutter plugin for the sourcepoint unified CMP,
  with integrations for Android and iOS - iOS implementation
version: 0.1.1
homepage: https://github.com/thekorn/sourcepoint_unified_cmp
repository: https://github.com/thekorn/sourcepoint_unified_cmp/tree/main/packages/sourcepoint_unified_cmp_ios

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: sourcepoint_unified_cmp
    platforms:
      ios:
        pluginClass: SourcepointUnifiedCmpPlugin
        dartPluginClass: SourcepointUnifiedCmpIOS

dependencies:
  flutter:
    sdk: flutter
  sourcepoint_unified_cmp_platform_interface: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^16.0.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.1.0
