name: sourcepoint_unified_cmp
description: sourcepoint unified cmp plugin for flutter
version: 0.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: sourcepoint_unified_cmp_android
      ios:
        default_package: sourcepoint_unified_cmp_ios

dependencies:
  flutter:
    sdk: flutter
  sourcepoint_unified_cmp_android: ^0.1.1
  sourcepoint_unified_cmp_ios: ^0.1.1
  sourcepoint_unified_cmp_platform_interface: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.6
  very_good_analysis: ^5.1.0
