name: sourcepoint_unified_cmp_android

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/sourcepoint_unified_cmp_android.yaml"
      - "packages/sourcepoint_unified_cmp_android/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/sourcepoint_unified_cmp_android.yaml"
      - "packages/sourcepoint_unified_cmp_android/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.22.1
      working_directory: packages/sourcepoint_unified_cmp_android
      coverage_excludes: "lib/src/*.g.dart"
      min_coverage: 0

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      min_score: 120
