name: sourcepoint_unified_cmp_android
description: flutter plugin for the sourcepoint unified CMP,
  with integrations for Android and iOS - Android implementation
version: 0.1.2
homepage: https://github.com/thekorn/sourcepoint_unified_cmp
repository: https://github.com/thekorn/sourcepoint_unified_cmp/tree/main/packages/sourcepoint_unified_cmp_android


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: sourcepoint_unified_cmp
    platforms:
      android:
        package: de.thekorn.sourcepoint.unified.cmp
        pluginClass: SourcepointUnifiedCmpPlugin
        dartPluginClass: SourcepointUnifiedCmpAndroid

dependencies:
  flutter:
    sdk: flutter
  sourcepoint_unified_cmp_platform_interface: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^16.0.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.1.0
