name: sourcepoint_unified_cmp_android
description: Android implementation of the sourcepoint_unified_cmp plugin
version: 0.1.0+1
publish_to: none


environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: sourcepoint_unified_cmp
    platforms:
      android:
        package: de.thekorn.sourcepoint.unified.cmp
        pluginClass: SourcepointUnifiedCmpPlugin
        dartPluginClass: SourcepointUnifiedCmpAndroid

dependencies:
  flutter:
    sdk: flutter
  sourcepoint_unified_cmp_platform_interface:
    path: ../sourcepoint_unified_cmp_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.1.0
